# Python 資料分析

> 重要觀念複習：函數、類別與模組（套件）

[數據交點](https://www.datainpoint.com/) | 郭耀仁 <yaojenkuo@datainpoint.com>

## 組織程式碼

## 什麼是組織程式碼？

面對不同目的以及應用場景，我們會有組織程式碼的需求，簡單來說，是希望程式碼可以簡潔且有效率地完成任務。

## 組織程式碼希望達到的目標最主要有兩個：

1. 提升程式碼的「可利用性」。
2. 減少程式碼的「重複」。

## Python 提供三種機制供使用者組織程式碼

視應用範疇由小到大依序為：

- 函數（Function）
- 類別（Class）
- 模組/套件（Module/Library）

## 如何理解程式碼組織機制

- 數行程式碼可以組織為一個函數。
- 數個函數可以組織為一個類別。
- 數個類別可以組織為一個模組。
- 數個模組可以組織為一個功能更多的模組。

## 程式碼，組織！

![](https://media.giphy.com/media/LOFT5Jd31ON1b5kLtP/giphy.gif)

來源：<https://gph.is/g/4bWWoxv>

## 函數

## 什麼是函數

一段被賦予名稱的程式碼，能夠完成某一個文字處理或者數值計算任務，使用（呼叫）某個函數之前，必須先確定這個函數在執行的範疇中已經被定義妥善。

## 「哈囉世界」Hello, World!

In [1]:
print("Hello, World!")

Hello, World!


## 「哈囉世界」中所使用的 `print` 是什麼？

- `print` 是 Python 的「內建函數」。
- 「內建」所指的意思是不需要先行「定義」就可以使用的函數。
- Python 的內建函數：<https://docs.python.org/3/library/functions.html>

## 一個函數由四個元件組成

1. 函數名稱
2. 輸入、參數
3. 函數主體
4. 輸出

## 函數運作的過程就像買一杯珍珠奶茶

![Imgur](https://i.imgur.com/6gpJebm.jpg?1)

來源: Google 圖片

## 函數有四個來源

- 來自「內建函數」：<https://docs.python.org/3/library/functions.html>
- 來自標準模組（套件）：<https://docs.python.org/3/library>
- 來自第三方模組（套件）。
- 來自使用者的定義。

## 來自「內建函數」

<https://docs.python.org/3/library/functions.html>

In [2]:
print(pow(5, 3))

125


## 來自標準模組（套件）

<https://docs.python.org/3/library>

In [3]:
from random import randint

print(randint(1, 11))

11


## 來自第三方模組（套件）

In [4]:
from numpy.random import randint

print(randint(1, 10, size=5))

[7 5 2 3 2]


## 來自使用者的定義

In [5]:
def power(x, n):
    out = x**n
    return out

print(power(5, 3))

125


## 輸入與參數在函數定義與使用（呼叫）時的差別

- 定義時稱為輸入（Inputs）或參數（Parameters）。
- 使用（呼叫）函數時稱為引數（Arguments）。

In [6]:
def power(x, n):
    out = x**n # Parameters
    return out

a = 5 # Argument
b = 3 # Argument
print(power(a, b)) # Arguments

125


## 參數與引數的差別

- 在自行定義的函數 `power(x, n)` 中 `x` 與 `n` 稱為輸入（Inputs）或參數（Parameters）。
- 在呼叫自行定義的函數 `power(a, b)` 中 `a` 與 `b` 稱為引數（Arguments）。

## 如何自行定義函數

- `def` 用來定義函數的名稱。
- `return` 用來標註函數的輸出。
- 縮排用來標註函數的主體。

## 自行定義函數的結構


```python
def function_name(INPUTS, PARAMETERS, ...):
    # body of function_name
    """
    docstring: print documentation when help is called
    """
    # sequence of statements
    return OUTPUTS
```

## `return` 的作用

- 回傳函數的預期輸出。
- 為函數的主體畫下終止符。

## 回傳函數的預期輸出

In [7]:
def power(x, n):
    """
    Equivalent to x raised to the power of n.
    """
    out = x**n

print(power(5, 3))

None


## 為函數的主體畫下終止符

In [8]:
def power(x, n):
    """
    Equivalent to x raised to the power of n.
    """
    print(x)
    print(n)
    out = x**n
    return out

print(power(5, 3))

5
3
125


## 即便寫在縮排的函數主體中，在 `return` 後所寫的程式並沒有作用

In [9]:
def power(x, n):
    """
    Equivalent to x raised to the power of n.
    """
    out = x**n
    return out
    print(x)
    print(n)

print(power(5, 3))

125


## 變數的作用域（scope）

> 在電腦程式設計中，作用域是名字與實體的繫結保持有效的那部分電腦程式。

來源: https://en.wikipedia.org/wiki/Scope_(computer_science)

## 簡而言之，存在有自行定義函數的狀態下，變數具有兩種類型

1. 區域（local）
2. 全域（global）

## 在函數的縮排中被宣告的是區域變數，僅有在縮排中才有效

In [10]:
def power(x, n):
    out = x**n
    print(x)
    print(n)
    print(out)
    return out

print(power(5, 3))

5
3
125
125


## 不是在函數縮排中被宣告的是全域變數，在任何地方都有效

In [11]:
x = 4
n = 2
out = x**n
def power():
    return out

print(x)
print(n)
print(out)
print(power())

4
2
16
16


## 考量輸入與輸出的對應關係

- 多個輸出
- 多個輸入

## 「多個輸出」對應關係以資料結構處理

- 預設以 `tuple` 資料結構應對多個輸出。
- 可以自行調整偏好的資料結構。

In [12]:
def first_three_characters(x):
    if len(x) < 3:
        return "Cannot extract the first three characters from input string."
    first_char, second_char, third_char = x[0], x[1], x[2]
    return first_char, second_char, third_char

print(first_three_characters("Python"))
print(type(first_three_characters("Python")))

('P', 'y', 't')
<class 'tuple'>


In [13]:
def first_three_characters(x):
    if len(x) < 3:
        return "Cannot extract the first three characters from input string."
    first_char, second_char, third_char = x[0], x[1], x[2]
    out = [first_char, second_char, third_char]
    return out

print(first_three_characters("Python"))
print(type(first_three_characters("Python")))

['P', 'y', 't']
<class 'list'>


In [14]:
def first_three_characters(x):
    if len(x) < 3:
        return "Cannot extract the first three characters from input string."
    first_char, second_char, third_char = x[0], x[1], x[2]
    out = {"1st": first_char,
           "2nd": second_char,
           "3rd": third_char}
    return out

print(first_three_characters("Python"))
print(type(first_three_characters("Python")))

{'1st': 'P', '2nd': 'y', '3rd': 't'}
<class 'dict'>


## 「多個輸入」對應關係以資料結構或彈性參數處理

- 使用資料結構作為一個輸入名稱。
- 使用彈性參數：
    - `*args`
    - `**kwargs`

In [15]:
def sum_and_square(x):
    summation = sum(x)
    out = summation**2
    return out

print(sum_and_square([2, 3, 5]))
print(sum_and_square((2, 3, 5, 7)))

100
289


## 彈性參數 `args` 可以在函數主體中以 `tuple` 形式運用

In [16]:
def sum_and_square(*args):
    print(type(args)) # tuple
    summation = sum(args)
    out = summation**2
    return out

print(sum_and_square(2, 3, 5))
print(sum_and_square(2, 3, 5, 7))

<class 'tuple'>
100
<class 'tuple'>
289


## 彈性參數 `kwargs` 可以在函數主體中以 `dict` 形式運用

In [17]:
def print_country_capital(**kwargs):
    print(type(kwargs)) # dict
    for key, value in kwargs.items():
        print("Country: {:<7} Capital: {}".format(key, value))

print_country_capital(Japan="Tokyo", USA="Washington D.C.", Taiwan="Taipei")

<class 'dict'>
Country: Japan   Capital: Tokyo
Country: USA     Capital: Washington D.C.
Country: Taiwan  Capital: Taipei


## 類別

## 兩種不同的撰寫程式方法

- 程序化程式設計（Procedural programming）。
- 物件導向程式設計（Object-oriented programming, OOP）。

## 程序化程式設計

以函數為主體的撰寫程式方法稱為「程序化程式設計（Procedural programming）」，把即將要執行的程式碼組織為函數，並依序呼叫這些函數來完成任務。

## 物件導向程式設計

除了程序化程式設計，另外一種在軟體開發中被採用的撰寫程式方法稱為「物件導向程式設計（Object-oriented programming, OOP）」。

## 「類別」是物件導向程式設計的第一步

- 定義類別是一種讓使用者自行設計資料類型或結構的機制。
- `type` 函數所顯示的 `class` 就是「類別」。
- 物件（Object）稱為類別的實例（Instance）。

## `luke` 物件是 `str` 類別的實例

In [34]:
luke = "Luke Skywalker" 
print(type(luke))

<class 'str'>


## `skywalkers` 物件是 `list` 類別的實例

In [35]:
skywalkers = ["Luke Skywalker", "Anakin Skywalker", "Darth Vadar"]
print(type(skywalkers))

<class 'list'>


## 類別之於物件的關係

- 類別如同藍圖一般的存在。
- 物件如同依照藍圖所打造出來的終端產品。

## 為什麼我們需要定義類別？

- 當內建函數或模組（套件）的函數無法滿足需求時，我們定義函數。
- 當內建類別或模組（套件）的類別無法滿足需求時，我們定義類別。

## 常用的內建類別

- 變數類型
    - `int`
    - `float`
    - `str`
    - `bool`
    - `NoneType`

## 常用的內建類別（續）

- 資料結構
    - `list`
    - `tuple`
    - `dict`
    - `set`

## 資料分析的模組（套件）類別

- 資料結構
    - `numpy.ndarray`
    - `pandas.Index`
    - `pandas.Series`
    - `pandas.DataFrame`

## 設計類別時可以定義函數與資料

- 與類別綁定的函數，在實例化後稱為物件的方法（Methods）。
- 與類別綁定的資料，在實例化後稱為物件的屬性（Attributes）。

## 使用內建函數 `dir` 檢視物件的方法與屬性

In [36]:
# luke 物件是 str 類別的實例
luke = "Luke Skywalker" 
print(dir(luke))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [37]:
# skywalkers 物件是 list 類別的實例
skywalkers = ["Luke Skywalker", "Anakin Skywalker", "Darth Vadar"]
print(dir(skywalkers))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


## 使用 `class` 保留字定義類別

```python
class ClassName:
    """
    docstring: print documentation when __doc__ attribute is accessed
    """
    pass
```

In [1]:
class SimpleCalculator:
    """
    This class creates a simple calculator that is unable to do anything.
    """
    pass

sc = SimpleCalculator()
print(type(sc))
print(dir(sc))
print(sc.__doc__)

<class '__main__.SimpleCalculator'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']

    This class creates a simple calculator that is unable to do anything.
    


## 在類別程式區塊中使用 `def` 保留字將函數與類別綁定

與類別綁定的函數，在實例化後稱為物件的方法。

```python
class ClassName:
    """
    docstring: print documentation when __doc__ attribute is accessed
    """
    def method_name(self):
        # sequence of statements
```

## 如何理解 `self` 的抽象概念？

- 物件是類別的實例。
- 類別所綁定的函數在實例化後是物件的方法，呼叫時要指定物件名稱。
- 實例化的物件名稱是由使用者所決定的。
- 想在定義類別的階段描述方法，必須要先給物件一個代稱：`self`。

In [39]:
class SimpleCalculator:
    """
    This class creates a simple calculator that is able to add 2 numbers.
    """
    def add(self, a, b):
        out = a + b
        return out

sc = SimpleCalculator() # self proxies object sc
print(sc.add(5, 6))

11


## `sc` 物件是 `SimpleCalculator` 類別的實例

- `sc` 物件有一個方法 `add(a, b)` 可以回傳兩數相加的結果。
- 使用 `sc.add(a, b)` 語法來呼叫方法。

## 在類別程式區塊中使用 `__init__` 函數將資料與類別綁定

- 與類別綁定的資料，在實例化後稱為物件的屬性。
- 開頭與結尾具有雙底線 `__` 的命名是 Python 的特殊命名，具備特殊用途。
- `__init__` 函數顧名思義就是在實例化（Instantialize）當下會被呼叫的函數。

```python
class ClassName:
    """
    docstring: print documentation when __doc__ attribute is accessed
    """
    def __init__(self, attributes):
        # sequence of statements
```

In [40]:
class SimpleCalculator:
    """
    This class creates a simple calculator that has 2 attributes.
    """
    def __init__(self, a, b):
        self.a = a
        self.b = b

sc = SimpleCalculator(5, 6) # self proxies object sc
print(sc.a)
print(sc.b)

5
6


## `sc` 物件是 `SimpleCalculator` 類別的實例

- `SimpleCalculator` 類別實例化成為 `sc` 物件的時候呼叫 `__init__` 函數。
- `__init__` 函數賦予了 `sc` 物件兩個屬性：
    - 使用 `sc.a` 語法來取用屬性 `a`。
    - 使用 `sc.b` 語法來取用屬性 `b`。

In [41]:
# 若想在類別程式區塊中使用屬性，可以 self.attribute 語法取用
class SimpleCalculator:
    """
    This class creates a simple calculator that has 2 attributes and 1 method.
    """
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def add(self):
        out = self.a + self.b # 以 self.a, self.b 語法取用
        return out

sc = SimpleCalculator(5, 6) # self proxies object sc
print(sc.add())

11


In [42]:
# 若想在類別程式區塊中使用方法，可以 self.method 語法呼叫
class SimpleCalculator:
    """
    This class creates a simple calculator that has 2 attributes and 2 methods.
    """
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def add(self):
        out = self.a + self.b
        return out
    def add_and_square(self):
        add_result = self.add() # 以 self.add() 語法呼叫
        out = add_result**2
        return out

sc = SimpleCalculator(5, 6) # self proxies object sc
print(sc.add_and_square())

121


## 在類別程式區塊中使用 `__repr__` 函數設計實例化之後物件在 `print` 函數的顯示

In [43]:
# 沒有 __repr__ 函數
class SimpleCalculator:
    """
    This class creates a simple calculator that has 2 attributes.
    """
    def __init__(self, a, b):
        self.a = a
        self.b = b
sc = SimpleCalculator(5, 6) # self proxies object sc
print(sc)

In [44]:
# 有 __repr__ 函數
class SimpleCalculator:
    """
    This class creates a simple calculator that has 2 attributes and 1 method.
    """
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def __repr__(self):
        out = "a: {}, b: {}".format(self.a, self.b)
        return out
    def add(self):
        out = self.a + self.b
        return out
sc = SimpleCalculator(5, 6) # self proxies object sc
print(sc)

a: 5, b: 6


## 使用 `ChildClass(ParentClass)` 語法繼承先前定義好的類別屬性、方法

In [45]:
class IntermediateCalculator(SimpleCalculator):
    pass
ic = IntermediateCalculator(5, 6)
print(ic)
print("a" in dir(ic))
print("b" in dir(ic))
print("add" in dir(ic))

a: 5, b: 6
True
True
True


## 繼承之後可以新增類別屬性

In [46]:
class IntermediateCalculator(SimpleCalculator):
    def __init__(self, a, b, c):
        SimpleCalculator.__init__(self, a, b)
        self.c = c
ic = IntermediateCalculator(5, 6, 7)
print("c" in dir(ic))

True


## 繼承之後可以新增、改寫類別方法

In [47]:
class IntermediateCalculator(SimpleCalculator):
    def __init__(self, a, b, c):
        SimpleCalculator.__init__(self, a, b)
        self.c = c
    def __repr__(self):
        out = "a: {}, b: {}, c: {}".format(self.a, self.b, self.c)
        return out
    def multiply(self):
        out = self.a * self.b * self.c
        return out
ic = IntermediateCalculator(5, 6, 7)
print(ic)
print("multiply" in dir(ic))

a: 5, b: 6, c: 7
True


## 資料分析師必須理解類別的定義

- 類別是一種將資料與函數與實例綁定的機制。
- 類別實例化之後被稱為物件，定義的資料與函數在此時就被改稱為
    - 資料：物件的「屬性」。
    - 函數：物件的「方法」。

## 類別同時扮演下列主題的「敲門磚」

- 物件導向程式設計。
- 資料結構與演算法。
- 設計模式。

## 模組（套件）

## 什麼是模組（套件）？

模組（Module）或者套件（Library）指的是以檔案或資料夾形式，來組織 Python 的函數以及類別。

## 檔案與資料夾形式

- 檔案的名稱為模組（套件）名，副檔名為 `.py`，例如 `my_module.py` 就是命名為 `my_module` 的模組（套件）。
- 檔案可以進一步收納到資料夾之中，資料夾的名稱為模組（套件）名，例如 `my_library` 就是命名為 `my_library` 的模組（套件）。

## 模組（套件）有三個來源

- 標準模組（套件）。
- 第三方模組（套件）。
- 來自使用者的定義。

## 使用 `import` 載入已安裝好的模組（套件）

- 以 `module` 命名使用。
- 或者以 `alias` 命名使用。
- 模組中的函數、類別都用 `.` 來表示從屬關係。

```python
import module
import module as alias
```

## 使用 `from module import feature` 載入模組（套件）中的部分功能

- 部分功能 `feature` 可以是函數或者類別。
- 模組中的函數、類別都用 `.` 來表示從屬關係。

```python
from module import function_name # from module import function_name as alias
from module import class_name    # from module import class_name as alias
```

## 標準模組（套件）

- 伴隨 Python 直譯器（安裝來自 <https://www.python.org> 的版本）而來的模組套件。
- <https://docs.python.org/3/library>

In [48]:
# 標準模組（套件）
import random
import random as rand
from random import randint

print(random.randint(1, 11))
print(rand.randint(1, 11))
print(randint(1, 11))

8
10
11


## 第三方模組（套件）

- 並非伴隨 Python 直譯器（安裝來自 <https://www.python.org> 的版本）而來的模組套件。
- 載入前要確認在環境中第三方模組（套件）已經安裝妥當
- 未安裝（或更新）在終端機（Anaconda Prompt) 以 `pip install -U module_name` 語法安裝（或更新）。

## 什麼是 `pip`？

`pip` 是 Python 的模組（套件）管理系統，可以用來從 [PyPI（Python Package Index）](https://pypi.org/)下載、安裝和管理模組（套件），目前的 Python 版本都會預先安裝 `pip`。

Source: <https://pip.pypa.io/en/stable>

In [49]:
#第三方模組（套件）
import numpy
import numpy as np
from numpy import random

print(numpy.random.randint(1, 10, size=5))
print(np.random.randint(1, 10, size=5))
print(random.randint(1, 10, size=5))

[9 3 9 9 1]
[4 2 3 1 6]
[1 9 6 8 2]


## 標準以及第三方模組（套件）的安裝路徑

- 標準模組（套件）安裝在 `path_to_python_env/lib/python3.x`。
- 第三方模組（套件）安裝在 `path_to_python_env/lib/python3.x/site-packages`。

## 來自使用者的定義

- 將函數、類別撰寫在工作目錄（Working directory）下副檔名為 `.py` 的檔案中。
- 若有多個檔案可以用一個資料夾收納起來。
- 檔案與資料夾就是模組（套件）命名，其中的函數、類別都用 `.` 來表示從屬關係。

## 在工作目錄新增 `simple_calculator.py`

複製貼上後存檔。

```python
class SimpleCalculator:
    """
    This class creates a simple calculator that has 2 attributes and 1 method.
    """
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def __repr__(self):
        out = "a: {}, b: {}".format(self.a, self.b)
        return out
    def add(self):
        out = self.a + self.b
        return out
```

In [50]:
from simple_calculator import SimpleCalculator

sc = SimpleCalculator(5, 6)
print(sc.add())

11


## 目前我們不需要自行建立模組（套件）

但我們應該要能區分模組（套件）中的函數、類別以及實例化後物件的屬性、方法。

In [51]:
import numpy as np

arr = np.array([2, 3, 5, 7, 11])  # the function of numpy library
print(arr.size)                   # the attribute of an arr object
print(arr.sum())                  # the method of an arr object

5
28
